FROM python:3.12-slim
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
#Expose the port for the API [cite: 31, 236]
EXPOSE 5000
CMD ["python", "backend/main.py"]